# Form implementation generated from reading ui file 'app/ui/win.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(599, 489)

        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resources/logo-02.jpg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Form.setWindowIcon(icon)

        Form.setStyleSheet("""
                    #Form {
                        background-color: rgb(181, 213, 202);
                    }
                    QPushButton {
                        background-color: rgb(224, 169, 175);
                        border: none;
                        border-radius: 6px;
                        font-size: 12pt;
                        color: rgb(0, 0, 0);
                        font-family: "MS Shell Dlg 2";
                    }
                    QPushButton:hover {
                        background-color: rgb(200, 150, 155);
                    }
                    QLabel {
                        font-size: 14pt;
                        color: rgb(0, 0, 0);
                        font-family: "MS Shell Dlg 2";
                    }
                    QLineEdit {
                        background-color: rgb(255, 255, 255);
                        border-radius: 6px;
                        font-size: 12pt;
                        color: rgb(0, 0, 0);
                        font-family: "MS Shell Dlg 2";
                        padding: 5px;

                    QMessage
                    }
                """)

        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(180, 250, 244, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(230, 30, 150, 150))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QtCore.QSize(150, 150))
        self.label_2.setPixmap(QtGui.QPixmap("resources/logo-01.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 310, 561, 151))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.fabric_remains_button = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.fabric_remains_button.setEnabled(True)
        self.fabric_remains_button.setMinimumSize(QtCore.QSize(0, 0))
        self.fabric_remains_button.setMaximumSize(QtCore.QSize(300, 70))
        self.fabric_remains_button.setObjectName("fabric_remains_button")
        self.verticalLayout.addWidget(self.fabric_remains_button)
        self.unuseful_write_offs_button = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.unuseful_write_offs_button.setEnabled(True)
        self.unuseful_write_offs_button.setMinimumSize(QtCore.QSize(0, 0))
        self.unuseful_write_offs_button.setMaximumSize(QtCore.QSize(300, 70))
        self.unuseful_write_offs_button.setObjectName("unuseful_write_offs_button")
        self.verticalLayout.addWidget(self.unuseful_write_offs_button)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.add_role_button = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.add_role_button.setMinimumSize(QtCore.QSize(0, 0))
        self.add_role_button.setMaximumSize(QtCore.QSize(300, 70))
        self.add_role_button.setObjectName("add_role_button")
        self.verticalLayout_3.addWidget(self.add_role_button)
        self.add_emp_button = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.add_emp_button.setMinimumSize(QtCore.QSize(0, 0))
        self.add_emp_button.setMaximumSize(QtCore.QSize(300, 70))
        self.add_emp_button.setObjectName("add_emp_button")
        self.verticalLayout_3.addWidget(self.add_emp_button)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Главное окно"))
        Form.setStyleSheet(_translate("Form", "\n"
"    #Form{\n"
"        background-color: rgb(181, 213, 202);\n"
"    }\n"
"    QPushButton{\n"
"        border: none;\n"
"        border-radius: 6px;\n"
"        font-size: 12pt;\n"
"        background-color: rgb(224, 169, 175);\n"
"    }\n"
"   "))
        self.label.setText(_translate("Form", "Учет затрат и остатков"))
        self.fabric_remains_button.setText(_translate("Form", "Остатки ткани\n"
"(можно использовать)"))
        self.unuseful_write_offs_button.setText(_translate("Form", "Списанные материалы\n"
"(нельзя использовать)"))
        self.add_role_button.setText(_translate("Form", "Добавить роль"))
        self.add_emp_button.setText(_translate("Form", "Добавить сотрудника"))


