from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1062, 687)
        self.icon_label = QtWidgets.QLabel(parent=Form)
        self.icon_label.setGeometry(QtCore.QRect(10, 10, 81, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.icon_label.sizePolicy().hasHeightForWidth())
        self.icon_label.setSizePolicy(sizePolicy)
        self.icon_label.setText("")
        self.icon_label.setPixmap(QtGui.QPixmap("uis\\../проект бабаева/logo-02.jpg"))
        self.icon_label.setScaledContents(True)
        self.icon_label.setObjectName("icon_label")
        self.title_label = QtWidgets.QLabel(parent=Form)
        self.title_label.setGeometry(QtCore.QRect(110, 30, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.title_label.setFont(font)
        self.title_label.setObjectName("title_label")
        self.scrollArea = QtWidgets.QScrollArea(parent=Form)
        self.scrollArea.setGeometry(QtCore.QRect(10, 100, 1041, 571))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1039, 569))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.materials_table = QtWidgets.QTableWidget(parent=self.scrollAreaWidgetContents)
        self.materials_table.setObjectName("materials_table")
        self.materials_table.setColumnCount(0)
        self.materials_table.setRowCount(0)
        self.horizontalLayout.addWidget(self.materials_table)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.layoutWidget_2 = QtWidgets.QWidget(parent=Form)
        self.layoutWidget_2.setGeometry(QtCore.QRect(590, 20, 153, 60))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.material_layout = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.material_layout.setContentsMargins(0, 0, 0, 0)
        self.material_layout.setObjectName("material_layout")
        self.material_label = QtWidgets.QLabel(parent=self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.material_label.setFont(font)
        self.material_label.setObjectName("material_label")
        self.material_layout.addWidget(self.material_label)
        self.material_combobox = QtWidgets.QComboBox(parent=self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.material_combobox.setFont(font)
        self.material_combobox.setObjectName("material_combobox")
        self.material_layout.addWidget(self.material_combobox)
        self.layoutWidget_3 = QtWidgets.QWidget(parent=Form)
        self.layoutWidget_3.setGeometry(QtCore.QRect(760, 20, 153, 60))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.reason_layout = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.reason_layout.setContentsMargins(0, 0, 0, 0)
        self.reason_layout.setObjectName("reason_layout")
        self.reason_label = QtWidgets.QLabel(parent=self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.reason_label.setFont(font)
        self.reason_label.setObjectName("reason_label")
        self.reason_layout.addWidget(self.reason_label)
        self.reason_combobox = QtWidgets.QComboBox(parent=self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.reason_combobox.setFont(font)
        self.reason_combobox.setObjectName("reason_combobox")
        self.reason_layout.addWidget(self.reason_combobox)
        self.graph_pushbutton = QtWidgets.QPushButton(parent=Form)
        self.graph_pushbutton.setGeometry(QtCore.QRect(930, 30, 111, 41))
        self.graph_pushbutton.setAutoFillBackground(False)
        self.graph_pushbutton.setObjectName("graph_pushbutton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.title_label.setText(_translate("Form", "Списанные материалы"))
        self.material_label.setText(_translate("Form", "Выбрать материал:"))
        self.reason_label.setText(_translate("Form", "Выбрать причину:"))
        self.graph_pushbutton.setText(_translate("Form", "Построить\n"
"график"))
